name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 3500
num_choices: 1

# a list of model to generate answers
model_list:
  - llama-3.1-70b-tulu3-sft
  # - llama-3.1-70b-instruct-rhelai
  # - llama-3-8b-instruct-simpo-sft-base-vanilla-32
  # - llama-3-8b-instruct-simpo-sft-base-route-32
  # - llama-3-8b-instruct-simpo-nh-domain-system-chat0-32
  # - llama-3-8b-instruct-simpo-nh-safety-32
  # - llama-3-8b-instruct-simpo-nh-vanilla-base-new-32
  # - llama-3-8b-instruct-simpo-nh-vanilla-route-32
  # - llama-3-8b-instruct-simpo-nh-vanilla-base-32
  # - llama-3-8b-instruct-simpo-nh-vanilla-32
  # - llama-3-8b-instruct-simpo-armo-32
  # - llama-3-8b-instruct-simpo-mistral-bt-v0-32
  # - merlinite-simpo-ratio-0.5-lr-3e-7-beta-18.0
  # - merlinite-simpo-ratio-0.5-lr-3e-7-beta-12.0

